### ISSUE TITLE
Mapping threatStatus

### ISSUE THREAD

**Issue by peterdesmet** [inbo/eurobutt-checklist#11]
Not all statuses in the source data are IUCN values. Need to decide how to map these:

```r
distribution %<>% mutate(threatStatus = recode(input_red_list_category,
  CR = "CR", # Critically endangered
  DD = "DD", # Data deficient
  EN = "EN", # Endangered
  LC = "LC", # Least concern
  NE = "NE", # Not evaluated
  "No Red List available" = "",
  NT = "NT", # Near threatened
  NtA = "?",
  R = "?",
  RE = "?",
  Unknown = "?",
  VU = "VU", # Vulnerable
  .default = ""
))
```

**Comment by DimEvil** [comment]
If I remember, we do not use only official IUCN values.  Most countries use their own interpretation. 
RE = regional endangered (can never be IUCN category or can never be translated)

**Comment by peterdesmet** [comment]
Suggestion by Dirk:

* `NtA` -> "NA" for "Not applicable", official, see https://www.iucnredlist.org/about/regional)
* `R` -> "Rare" (not official, used by Germany)
* `RE` -> "RE" for "Regionally Extinct", official, see https://www.iucnredlist.org/about/regional)
* `Unknown` -> "Unknown"
