### ISSUE TITLE
Species without higher classification

### ISSUE THREAD

**Issue by peterdesmet** [inbo/eurobutt-checklist#16]
All butterfly species in distributions have a matching higher classification in the `taxa` spreadsheet, except the ones below, probably because no match in GBIF was found.

@dirkmaes33 @DimEvil Do we try to complete missing information for those species, especially those with a (non regional) `scientific name`?

decision | regional name | scientific name | regions | comments
--- | --- | --- | --- | ---
? | [Aricia hyacinthus](https://www.gbif.org/species/5140131) | NA | EU27, EUR, RO | Not present according to Rudi Verovnik
? | [Belenois aurota](https://www.gbif.org/species/1919181) | NA | MT | Probably accidentally introduced
? | [Colias lesbia](https://www.gbif.org/species/5137588) | NA | MT | Misidentification
? | [Deudorix livia](https://www.gbif.org/species/10656713) | NA | CY, GR | Single specimen captured in 1994,  Species added. Recorded once in NE Attica, Greece; Müller et al. (2005)
[Lasiommata deidamia](https://github.com/inbo/eurobutt-checklist/issues/16#issuecomment-583342914) ?? | Lopinga deidamia | NA | EU27, EUR | 
? | Paleophilotes panope | Palaeophilotes panope | RU | Comment Rudi: not a European species
? | [Papilio saharae](https://www.gbif.org/species/1937791) | NA | MT | Misidentification by Leraut (2016)
[Polyommatus orphicus](https://github.com/inbo/eurobutt-checklist/issues/16#issuecomment-583342169) ?? | [Polyommatus eleniae](https://www.gbif.org/species/5772735) | Polyommatus eleniae | EU27, EUR | Does not occur in Europe
[Polyommatus damone](https://github.com/inbo/eurobutt-checklist/issues/16#issuecomment-583343919) ?? | [Polyommatus pljushtchi](https://www.gbif.org/species/5772753) | Polyommatus damone? | EU27, EUR | CHECK SCIENTIFIC NAME
? | Pseudophilotes panope | Palaeophilotes panope | EU27, EUR | Comment Rudi: not a European species
? | [Thaleropis ionia](https://www.gbif.org/species/1896915) | NA | GR | Kudrna (1986)

**Comment by peterdesmet** [comment]
The `taxa` spreadsheet only contains species officially listed on Wiemers et al. (2018, https://doi.org/10.3897/zookeys.811.28712). I think we should therefore not include the above regional names that we could not match (11 names, 18 distributions).
R: I agree

**Comment by peterdesmet** [comment]
From that same article (https://doi.org/10.3897/zookeys.811.28712):

> Polyommatus eleniae: Considered conspecific with Polyommatus orphicus based on the equal haploid chromosome number and no differences in mitochondrial DNA – barcoding gene (Vishnevskaya et al. 2016).

**Comment by peterdesmet** [comment]
Is `Lopinga deidamia` a synonym of `Lasiommata deidamia (Eversmann, 1851)`?

**Comment by peterdesmet** [comment]
From the article:

> Polyommatus pljushtchi: Species status is based on erroneous sequences (opinion in Kudrna et al. (2011); Shapoval and Lukhtanov (2015).) Considered here as ssp. of Polyommatus damone (Eversmann, 1841).

From spreadsheet:

> Comment Yurii Geryak: Polyommatus pljushtchi is a valid species. European endemic, restricted to the Crimea; not according to Wiemers et al. (in prep)

**Comment by dirkmaes33** [comment]
Aricia hyacinthus is accepted by GBIF (https://www.gbif.org/species/5140131) but not by Wiemers et al. (2018) ... Wiemers et al decided what is a species and what not and I am not going to argue with them about that.
Most of the other species are only very accidentally seen in Europe, but do have accepted names in GBIF

**Comment by peterdesmet** [comment]
Was already implemented. Checklist will only contain names from Wiemers et al.
