### ISSUE TITLE
Mapping status

### ISSUE THREAD

**Issue by peterdesmet** [inbo/eurobutt-checklist#18]
This was already discussed in #12, but since then there are more statuses. For mapped values, see definitions at http://rs.gbif.org/vocabulary/gbif/occurrence_status.xml

- [x] ~`A` = `absent`~
- [ ] ~`Ex` = `excluded`?~
- [ ] ~`Excluded` = `excluded`?~
- [ ] ~`I` = `irregular`?~
- [x] ~`M` = `absent` Is regular migrant, but decided in #12 to use "absent" rather than "irregular" or "present"~
- [x] ~`P` = `present`~
- [ ] ~`P?`= ?~
- [ ] ~`P(I)` = ?~

See https://github.com/inbo/eurobutt-checklist/issues/18#issuecomment-630701542

**Comment by dirkmaes33** [comment]
The link to the definitions is dead!

Abbreviations are given in this paper: https://zookeys.pensoft.net/article/28712/

P? = probably present
P(I) = Probably only present as an immigrant

**Comment by peterdesmet** [comment]
I have updated the link above. @dirkmaes33 GBIF uses the values below. I have attempted to map our values as best as possible, but please verify:

class | subclass | includes also | mapping
--- | --- | --- | ---
present | | endemic, native, extant | P
present | common | frequent, fairly common | 
present | rare | uncommon, casual | 
present | irregular | ephemeral, episodic, vagrant | I, P(I), M
doubtful | | possibly extant, probably extant, possibly extinct, presence uncertain | P?
absent | | extinct, extirpated | A, Ex
absent | excluded | misidentification, reported in error, erroneous | Excluded

Especially `I`, `P(I)`, `M` are a bit tricky to match: but since they all indicate presence due to migration, I would group them under `irregular`. To be consistent, that means not choosing `absent` for `M` @dirkmaes33 agree?

**Comment by dirkmaes33** [comment]
Absent for M is not correct, they are migrants that occur in a region every summer, just like Vanessa cardui (Distelvlinder) does here ... Migrant is the only correct term and it is strange that GBIF does not have it in the list. Many migrating birds are just like that (only present in summer and elsewhere in winter) and I wonder how they deal with it ... All M's in the list should be treated as migrating birds!

**Comment by peterdesmet** [comment]
Absent for `M` was suggested a while ago by you: https://github.com/inbo/eurobutt-checklist/issues/12#issuecomment-444018017. But, let's be defiant and use our own terms then (which will cause some distributions not to be parsed, but at least be correct):

eurobutt | map as | GBIF
--- | --- | ---
P | present | ok
I | irregular | ok
P(I) | irregular | ok
M | migrant | error
P? | doubtful | ok
Ex | absent | ok (we already indicate regionally extinct in threat status)
A | absent | ok
Excluded | excluded | ok

@dirkmaes33 agree with above mapping?

**Comment by dirkmaes33** [comment]
OK, everything depends on what the definition of "present" is ... If that means present all year long, than many birds will fall in the categorie absent!

**Comment by peterdesmet** [comment]
Indeed, but I will thus map as above.
