### ISSUE TITLE
Include islands of Macaronesian archipelagos 

### ISSUE THREAD

**Issue by peterdesmet** [inbo/eurobutt-checklist#20]
In response to https://github.com/inbo/eurobutt-checklist/issues/15#issuecomment-630614186

> The species with an empty column here are the ones from the individual Macaronesian archipelagos. For analysis, I just used a species' presence in the archipelago as a whole (3 possible regions) and not on every single island. I would publish the species for the individual archipelagos on a seperate sheet (as is done) and only keep the archipelago presence in the European sheet (if that is clear ...?).

I have included the archipelago and the islands, as that is interesting information we have and can thus publish. So, for one species we can have:

locationID | locality | countryCode | source 
--- | --- | --- | ---
http://marineregions.org/mrgid/3743 | Canary Islands | ES | Báez and Oromí (2010) | Martin Wiemers (pers. comm.) | Tennent (2005)
http://marineregions.org/mrgid/3747 | El Hierro, Canary Islands | ES | 
http://marineregions.org/mrgid/3744 | La Gomera, Canary Islands | ES | 
http://marineregions.org/mrgid/3748 | La Palma, Canary Islands | ES | 
http://marineregions.org/mrgid/3756 | Tenerife, Canary Islands | ES | 
http://marineregions.org/mrgid/4955 | Madeira | PT | Martin Wiemers (pers. comm.) | Tennent (2005)
http://marineregions.org/mrgid/4956 | Madeira, Madeira | PT | 

@dirkmaes33 Is that ok? I could remove `Madeira, Madeira` (even though it has a different code) as that is somewhat duplicate information?

**Comment by dirkmaes33** [comment]
The Madeira archipelago consists of  islands: Madeira and Porto Santo so I would suggest to keep, "Madeira, Madeira" ...

**Comment by peterdesmet** [comment]
Oh, yes, oversight. Ok, I will leave mapping as is then.
