### ISSUE TITLE
Clean up Rmd files

### ISSUE THREAD

**Issue by peterdesmet** [inbo/eurobutt-checklist#5]
- [x] `read_data.Rmd`: @LienReyserhove script to use to read from GS, ~~match with GBIF and write to interim~~
- [x] `dwc_mapping.Rmd`: @DimEvil basis for full DwC mapping from interim files.
    - Remove any name match functionality
    - Read interim EU taxa => taxon core + EU distribution
    - Read interim regional taxa => link to taxon core using EU name + add distribution rows for the countries
- [x] `weighted_red_list_values.Rmd`: @LienReyserhove file to use for @dirkmaes33 code
- [x] `Species Red list Butterflies Locale RMD.Rmd`: @LienReyserhove move name match functionality to read_data.Rmd and then remove script
- [x] `convert_to_dwc.R`: legacy script, remove eventually
- [x] `template Rmd.Rmd`: remove script

**Comment by peterdesmet** [comment]
Decided with @DimEvil that there is no need to match names with GBIF as we don't need any extra information from GBIF. That means that the read step becomes very simple and could as well be integrated in `dwc_mapping.Rmd`. For now, we have kept it as a separate Rmd.

**Comment by DimEvil** [comment]
We do need to change the readme.md file, according to the latest workflow.

**Comment by DimEvil** [comment]
Attempt to adapt readme.md

**Comment by peterdesmet** [comment]
Cleanup done in #14
